// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	sqs "github.com/aws/aws-sdk-go-v2/service/sqs"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, input
func (_m *Client) Publish(ctx context.Context, input *sqs.SendMessageInput) error {
	ret := _m.Called(ctx, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqs.SendMessageInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResolveQueueUrl provides a mock function with given fields: ctx, queueName
func (_m *Client) ResolveQueueUrl(ctx context.Context, queueName string) (*string, error) {
	ret := _m.Called(ctx, queueName)

	var r0 *string
	if rf, ok := ret.Get(0).(func(context.Context, string) *string); ok {
		r0 = rf(ctx, queueName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, queueName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
